### ISSUE TITLE
iOSSafari、AndroidChromeでのプロファイリングとボトルネックの特定

### ISSUE THREAD

**Issue by legokichi** [Ikagaka/cuttlebone#17]

**Comment by legokichi** [comment]
fb2e066c9cee1a148e8bf6891b41aff38eb3a5fa
時点での
https://ikagaka.github.io/cuttlebone/demo/
の
バージョン 44.0.2391.0 canary (64-bit)
でのプロファイル結果
http://gyazo.com/0732247e33feeb787d93758428f262ec
環境はMBA
http://gyazo.com/c74c396b6d7ea1adf874432d8ac04247

Mobile SafariのログはSafari側のinspectorがnarダウンロード時に落ちるので取れなかった

**Comment by legokichi** [comment]
narのダウンロードにおよそ3秒。
http://gyazo.com/4c9c58971762e935d20d87a2e19bd330
jszipによるnar解凍に1秒ちょいかかっておりコールスタックも深い。
次に全surface*.pngの透過処理が1.5秒くらいかかってる。

**Comment by legokichi** [comment]
1. 抜き色処理をUint8ClampedArrayにして複数workerで並列化すれば速くなりそう。
2. NarLoaderが解凍を遅延すれば処理が軽くなりそう
3. updates2.dauを利用して必要になったファイルから遅延ダウンロード( issue #14 )

1にはnarの大部分を占めるpngファイルの解凍つまり2が必須なので、高速化という点では1が求められている。
3ならnarのダウンロードでメインスレッドがアイドルしている時間を使って1が可能になるので、サーフェス表示までの大幅な時間短縮が可能になりそう。

心配していたarraybufferメモリ量は上記の高速化案の前では優先度低そうです。

**Comment by legokichi** [comment]
NarLoaderが解凍を遅延すれば処理が軽くなりそう

**Comment by legokichi** [comment]
updates2.dauの利用でnarのダウンロード時間とunzipの時間を減らせるので有用では

**Comment by legokichi** [comment]
#14は

**Comment by Narazaka** [comment]
うちでもIkagaka.demoではかってみました。(デフォルトゴースト・ずん子インストール・デフォルトゴースト起動)
おおざっぱに注釈っぽい感じでしょうか。
ZIPがどこかはよくわからず
抜き色処理はシェル量に対して有意に処理時間が増加する感じ。
![image2](https://cloud.githubusercontent.com/assets/1712548/7466204/d381e16c-f319-11e4-84b6-874e6cc75a92.png)

**Comment by Narazaka** [comment]
XHRがはやいのはキャッシュの分かもしれません。

**Comment by Narazaka** [comment]
なお環境
![image3](https://cloud.githubusercontent.com/assets/1712548/7466241/7df0a9c6-f31a-11e4-9487-f653404b3226.png)

**Comment by legokichi** [comment]
赤字XHRが解凍、その直前の空白がnarダウンロードですね

**Comment by Narazaka** [comment]
なるほど

**Comment by legokichi** [comment]
https://twitter.com/duxca/status/595589139841437696
http://gyazo.com/eaa85639fa02eba93da478646299013b
透過処理ではgetImageDataがクソ遅いという話

**Comment by legokichi** [comment]
https://twitter.com/duxca/status/595605257683488769
transImageがクソ重いのでシェルロード時に透過処理せずcomposeElements時に毎回透過処理する

**Comment by legokichi** [comment]
最悪pngjs使う

**Comment by legokichi** [comment]
http://gyazo.com/43c2ad265b8dfd858dc778d56ac97ca4

cuttlebone@0.1.0での測定。ローカル。
透過処理の呼び出し回数を減らすことで、シェルのロード時間がおよそ1秒になり以前よりおよそ0.5秒速くなりました。

**Comment by legokichi** [comment]
http://gyazo.com/375f2a5ca2ea14ec77d0b2682b9ffdfc
cuttlebone:pngjs ブランチ b5d6e9471c9fcaea24f3826241f01d2eff8a1bbe での計測結果
getImageDataの遅延がなくなったがcuttlebone@0.1.0とは大して速度変わらず。
並列化と最適化をすれば倍くらいには速くなれそうなポテンシャルありそう

**Comment by legokichi** [comment]
結局サーフェス描画直前までgetImageDataしないことにした
