### ISSUE TITLE
ソースコードの占有化は避けるべき

### ISSUE THREAD

**Issue by legokichi** [Ikagaka/cuttlebone#38]
cuttleboneという名前をつけてまとめたのは良いが、legokichiさんはnarazakaさんとの縄張り争いをしているように見える

**Comment by legokichi** [comment]
おっしゃっていることはもっともです。

cuttleboneは各クラスライブラリの統合ビルド環境だけ提供して、ライブラリは以前のようにShell.js、Balloon.jsに分離する予定です。

cuttleboneという名前をつけて描画系を一つにまとめたのは今までの抽象化が下手で、Balloon.jsがスカスカなのにScope.jsが膨れ上がるようなことになっており、そのような適切な抽象化されていない状態で各クラスライブラリを行き来して修正していくのは困難だと感じたからです。

**Comment by Narazaka** [comment]
謎の一人芝居が
